[project]
name = "bucharest-urban-mobility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.3.6",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.uv]
package = false